// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public interface ActiveAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActiveAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  java.util.List<com.smartcity.emergency.Alert> 
      getAlertsList();
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  com.smartcity.emergency.Alert getAlerts(int index);
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  java.util.List<? extends com.smartcity.emergency.AlertOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  com.smartcity.emergency.AlertOrBuilder getAlertsOrBuilder(
      int index);
}
