// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

/**
 * Protobuf type {@code ActiveAlertsResponse}
 */
public  final class ActiveAlertsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ActiveAlertsResponse)
    ActiveAlertsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActiveAlertsResponse.newBuilder() to construct.
  private ActiveAlertsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActiveAlertsResponse() {
    alerts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActiveAlertsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActiveAlertsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              alerts_ = new java.util.ArrayList<com.smartcity.emergency.Alert>();
              mutable_bitField0_ |= 0x00000001;
            }
            alerts_.add(
                input.readMessage(com.smartcity.emergency.Alert.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        alerts_ = java.util.Collections.unmodifiableList(alerts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartcity.emergency.EmergencyProto.internal_static_ActiveAlertsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartcity.emergency.EmergencyProto.internal_static_ActiveAlertsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartcity.emergency.ActiveAlertsResponse.class, com.smartcity.emergency.ActiveAlertsResponse.Builder.class);
  }

  public static final int ALERTS_FIELD_NUMBER = 1;
  private java.util.List<com.smartcity.emergency.Alert> alerts_;
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  public java.util.List<com.smartcity.emergency.Alert> getAlertsList() {
    return alerts_;
  }
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  public java.util.List<? extends com.smartcity.emergency.AlertOrBuilder> 
      getAlertsOrBuilderList() {
    return alerts_;
  }
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  public int getAlertsCount() {
    return alerts_.size();
  }
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  public com.smartcity.emergency.Alert getAlerts(int index) {
    return alerts_.get(index);
  }
  /**
   * <code>repeated .Alert alerts = 1;</code>
   */
  public com.smartcity.emergency.AlertOrBuilder getAlertsOrBuilder(
      int index) {
    return alerts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < alerts_.size(); i++) {
      output.writeMessage(1, alerts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < alerts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, alerts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartcity.emergency.ActiveAlertsResponse)) {
      return super.equals(obj);
    }
    com.smartcity.emergency.ActiveAlertsResponse other = (com.smartcity.emergency.ActiveAlertsResponse) obj;

    if (!getAlertsList()
        .equals(other.getAlertsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAlertsCount() > 0) {
      hash = (37 * hash) + ALERTS_FIELD_NUMBER;
      hash = (53 * hash) + getAlertsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartcity.emergency.ActiveAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartcity.emergency.ActiveAlertsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ActiveAlertsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ActiveAlertsResponse)
      com.smartcity.emergency.ActiveAlertsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartcity.emergency.EmergencyProto.internal_static_ActiveAlertsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartcity.emergency.EmergencyProto.internal_static_ActiveAlertsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartcity.emergency.ActiveAlertsResponse.class, com.smartcity.emergency.ActiveAlertsResponse.Builder.class);
    }

    // Construct using com.smartcity.emergency.ActiveAlertsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAlertsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (alertsBuilder_ == null) {
        alerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        alertsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartcity.emergency.EmergencyProto.internal_static_ActiveAlertsResponse_descriptor;
    }

    @java.lang.Override
    public com.smartcity.emergency.ActiveAlertsResponse getDefaultInstanceForType() {
      return com.smartcity.emergency.ActiveAlertsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartcity.emergency.ActiveAlertsResponse build() {
      com.smartcity.emergency.ActiveAlertsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartcity.emergency.ActiveAlertsResponse buildPartial() {
      com.smartcity.emergency.ActiveAlertsResponse result = new com.smartcity.emergency.ActiveAlertsResponse(this);
      int from_bitField0_ = bitField0_;
      if (alertsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          alerts_ = java.util.Collections.unmodifiableList(alerts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alerts_ = alerts_;
      } else {
        result.alerts_ = alertsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartcity.emergency.ActiveAlertsResponse) {
        return mergeFrom((com.smartcity.emergency.ActiveAlertsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartcity.emergency.ActiveAlertsResponse other) {
      if (other == com.smartcity.emergency.ActiveAlertsResponse.getDefaultInstance()) return this;
      if (alertsBuilder_ == null) {
        if (!other.alerts_.isEmpty()) {
          if (alerts_.isEmpty()) {
            alerts_ = other.alerts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlertsIsMutable();
            alerts_.addAll(other.alerts_);
          }
          onChanged();
        }
      } else {
        if (!other.alerts_.isEmpty()) {
          if (alertsBuilder_.isEmpty()) {
            alertsBuilder_.dispose();
            alertsBuilder_ = null;
            alerts_ = other.alerts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            alertsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAlertsFieldBuilder() : null;
          } else {
            alertsBuilder_.addAllMessages(other.alerts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartcity.emergency.ActiveAlertsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartcity.emergency.ActiveAlertsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.smartcity.emergency.Alert> alerts_ =
      java.util.Collections.emptyList();
    private void ensureAlertsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        alerts_ = new java.util.ArrayList<com.smartcity.emergency.Alert>(alerts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.smartcity.emergency.Alert, com.smartcity.emergency.Alert.Builder, com.smartcity.emergency.AlertOrBuilder> alertsBuilder_;

    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public java.util.List<com.smartcity.emergency.Alert> getAlertsList() {
      if (alertsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alerts_);
      } else {
        return alertsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public int getAlertsCount() {
      if (alertsBuilder_ == null) {
        return alerts_.size();
      } else {
        return alertsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public com.smartcity.emergency.Alert getAlerts(int index) {
      if (alertsBuilder_ == null) {
        return alerts_.get(index);
      } else {
        return alertsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder setAlerts(
        int index, com.smartcity.emergency.Alert value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.set(index, value);
        onChanged();
      } else {
        alertsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder setAlerts(
        int index, com.smartcity.emergency.Alert.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.set(index, builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder addAlerts(com.smartcity.emergency.Alert value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.add(value);
        onChanged();
      } else {
        alertsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder addAlerts(
        int index, com.smartcity.emergency.Alert value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.add(index, value);
        onChanged();
      } else {
        alertsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder addAlerts(
        com.smartcity.emergency.Alert.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.add(builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder addAlerts(
        int index, com.smartcity.emergency.Alert.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.add(index, builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder addAllAlerts(
        java.lang.Iterable<? extends com.smartcity.emergency.Alert> values) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alerts_);
        onChanged();
      } else {
        alertsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder clearAlerts() {
      if (alertsBuilder_ == null) {
        alerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        alertsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public Builder removeAlerts(int index) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.remove(index);
        onChanged();
      } else {
        alertsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public com.smartcity.emergency.Alert.Builder getAlertsBuilder(
        int index) {
      return getAlertsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public com.smartcity.emergency.AlertOrBuilder getAlertsOrBuilder(
        int index) {
      if (alertsBuilder_ == null) {
        return alerts_.get(index);  } else {
        return alertsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public java.util.List<? extends com.smartcity.emergency.AlertOrBuilder> 
         getAlertsOrBuilderList() {
      if (alertsBuilder_ != null) {
        return alertsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alerts_);
      }
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public com.smartcity.emergency.Alert.Builder addAlertsBuilder() {
      return getAlertsFieldBuilder().addBuilder(
          com.smartcity.emergency.Alert.getDefaultInstance());
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public com.smartcity.emergency.Alert.Builder addAlertsBuilder(
        int index) {
      return getAlertsFieldBuilder().addBuilder(
          index, com.smartcity.emergency.Alert.getDefaultInstance());
    }
    /**
     * <code>repeated .Alert alerts = 1;</code>
     */
    public java.util.List<com.smartcity.emergency.Alert.Builder> 
         getAlertsBuilderList() {
      return getAlertsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.smartcity.emergency.Alert, com.smartcity.emergency.Alert.Builder, com.smartcity.emergency.AlertOrBuilder> 
        getAlertsFieldBuilder() {
      if (alertsBuilder_ == null) {
        alertsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.smartcity.emergency.Alert, com.smartcity.emergency.Alert.Builder, com.smartcity.emergency.AlertOrBuilder>(
                alerts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        alerts_ = null;
      }
      return alertsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ActiveAlertsResponse)
  }

  // @@protoc_insertion_point(class_scope:ActiveAlertsResponse)
  private static final com.smartcity.emergency.ActiveAlertsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartcity.emergency.ActiveAlertsResponse();
  }

  public static com.smartcity.emergency.ActiveAlertsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActiveAlertsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ActiveAlertsResponse>() {
    @java.lang.Override
    public ActiveAlertsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActiveAlertsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActiveAlertsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActiveAlertsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartcity.emergency.ActiveAlertsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

