// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string zone = 1;</code>
   * @return The zone.
   */
  java.lang.String getZone();
  /**
   * <code>string zone = 1;</code>
   * @return The bytes for zone.
   */
  com.google.protobuf.ByteString
      getZoneBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
