// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.smartcity.emergency;

public final class EmergencyProto {
  private EmergencyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActiveAlertsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActiveAlertsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Alert_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017emergency.proto\"?\n\014AlertRequest\022\014\n\004zon" +
      "e\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\023\n\013description\030\003 \001" +
      "(\t\"<\n\rAlertResponse\022\n\n\002id\030\001 \001(\t\022\016\n\006statu" +
      "s\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\"\007\n\005Empty\".\n\024Act" +
      "iveAlertsResponse\022\026\n\006alerts\030\001 \003(\0132\006.Aler" +
      "t\"B\n\005Alert\022\n\n\002id\030\001 \001(\t\022\014\n\004zone\030\002 \001(\t\022\014\n\004" +
      "type\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\t2p\n\020Emergen" +
      "cyService\022*\n\tSendAlert\022\r.AlertRequest\032\016." +
      "AlertResponse\0220\n\017GetActiveAlerts\022\006.Empty" +
      "\032\025.ActiveAlertsResponseB+\n\027com.smartcity" +
      ".emergencyB\016EmergencyProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlertRequest_descriptor,
        new java.lang.String[] { "Zone", "Type", "Description", });
    internal_static_AlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlertResponse_descriptor,
        new java.lang.String[] { "Id", "Status", "Message", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_ActiveAlertsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ActiveAlertsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActiveAlertsResponse_descriptor,
        new java.lang.String[] { "Alerts", });
    internal_static_Alert_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Alert_descriptor,
        new java.lang.String[] { "Id", "Zone", "Type", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
